---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/_data
  label: People
  create: all
  match: "**/*"
  exclude: site.yml
- type: heading
  label: Content
- type: directory
  path: src/film
  label: Film
  create: all
  match: "**/*"
- type: directory
  path: src/movement
  label: Movement
  create: all
  match: "**/*"
- type: directory
  path: src/creators
  label: Creators
  create: all
  match: "**/*"
- type: directory
  path: src/connect
  label: Connect
  create: all
  match: "**/*"
- type: heading
  label: People
- type: document
  path: src/_data/protagonistList
  label: Protagonists
  match: "**/*"
upload_dir: transmodernity
public_path: transmodernity
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn start
