lang: en
name: transmodernity
title: transmodernity
# see https://ogp.me/#types
type: website
url: https://www.transmodernity.org
image: https://avatars3.githubusercontent.com/u/447956?s=400&v=4
description: Transmodernity is the New Now. It describes the emerging socio-cultural, economic, political, spiritual and philosophical shift of today, acknowledging the interconnectivity and interdependency of everything.
