lang: en
name: transmodernity
title: transmodernity
# see https://ogp.me/#types
type: website
url: https://www.transmodernity.org
image: https://res.cloudinary.com/tonipanoche/image/upload/v1595266305/transmodernity/TM_socials6.jpg
description: Transmodernity is the New Now. It describes the emerging socio-cultural, economic, political, spiritual and philosophical shift of today, acknowledging the interconnectivity and interdependency of everything.
